name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: ".github, .vscode, node_modules, dist, test, expressLib/node_modules, .dockerignore, .eslintrc.js, .gitignore, .gitpod.yaml, .prettierrc, tsconfig.json, tsconfig.build.json, README.md, yarn.lock, package.lock.json,package.json, expressLib/package.json, expressLib/package.lock.json nest-clie.json, Dockerfile"
